# Generated by Django 4.2.3 on 2023-08-13 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='date_upload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 13, 16, 45, 18, 408510), null=True),
        ),
    ]
