# Generated by Django 4.2.3 on 2023-08-20 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_files', '0003_competitivenes_alter_uploadedfiles_date_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitivenes',
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='date_upload',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 1, 14, 2, 783770), null=True),
        ),
    ]
